import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react';
import { Logger, ILogObj } from 'tslog';

interface TestImage {
  id: bigint;
  imageName: string;
  user: string;
  count: bigint;
}

interface TestImageApiResponse {
  images: TestImage[];
  total: number;
  pageSize: number;
  current: number;
}

const log: Logger<ILogObj> = new Logger();

const baseUrl =
  process.env.NODE_ENV === 'development'
    ? '/mockData' // 开发环境使用本地文件
    : 'https://dummyjson.com/'; // 生产环境使用线上 API

// Define a service using a base URL and expected endpoints
export const testImagesApiSlice = createApi({
  baseQuery: fetchBaseQuery({ baseUrl }),
  reducerPath: 'testImageApi',
  tagTypes: ['testImages'],
  endpoints: (build) => ({
    getTestImages: build.query<TestImageApiResponse, { limit?: number; page?: number }>({
      query: ({ limit = 20, page = 1 }) => {
        if (process.env.NODE_ENV === 'development') {
          return 'images.json';
        } else {
          return `images?limit=${limit}&page=${page}`;
        }
      },
      providesTags: (result, error, { limit, page }) =>
        result ? [{ type: 'testImages', id: `PAGE_${page}_LIMIT_${limit}` }] : [],
      transformResponse: (response: any) => {
        // 检查返回的数据结构
        log.info(response);
        return response; // 确保你返回了处理后的数据
      },
    }),
  }),
});

// Hooks are auto-generated by RTK-Query
// Same as `quotesApiSlice.endpoints.getQuotes.useQuery`
export const { useGetTestImagesQuery } = testImagesApiSlice;
